"""Plain-language interpretation generated by code, so a small model does not have to invent
wording. Evaluations showed that cheap models copy numbers correctly but lose points when they
phrase things themselves ("views fell 44%" for a share change, "Poland" for Polish Wikipedia,
"clearly declining" on moderate evidence, forgotten caveats). This module writes those
sentences once, correctly; the agent translates them and adds the product recommendation.
"""
from __future__ import annotations

from .langs import lang_name
from .rank import DEFAULT_WEIGHTS, rank

WORDING = {
    "strong_growth": "clearly growing", "growth": "growing (moderate evidence)",
    "possible_growth": "possibly growing, but the evidence is weak",
    "stable": "roughly stable",
    "strong_decline": "clearly declining", "decline": "declining (moderate evidence)",
    "possible_decline": "possibly declining, but the evidence is weak",
    "insufficient_data": "impossible to judge: too little data",
}
_WEIGHT_NAMES = {"growth": "momentum", "volume": "audience size", "share": "share of the wiki",
                 "confidence": "evidence quality"}


def _pct(x: float | None) -> str:
    return "n/a" if x is None else f"{x:+.1f}%"


def _int(x: float | int | None) -> str:
    return "n/a" if x is None else f"{int(round(x)):,}"


def series_label(lang: str, topic: str | None = None) -> str:
    base = f"{lang_name(lang)}-language Wikipedia ({lang})"
    return f"{topic} on {base}" if topic else base


def confidence_reasons(r: dict) -> str:
    m = r["metrics"]
    plain_ok = {
        "history": "two full years of data",
        "volume": f"a solid audience (median {m['median_daily_views']:g} views per day)",
        "significance": "the month-to-month trend is statistically clear" if r["direction"] in ("up", "down")
        else "no clear trend in either direction",
        "robust_to_spikes": "the change is not driven by one-off spike days",
        "concentration": "views are spread over the year rather than a few days",
        "normalization_agrees": "the result holds after adjusting for wiki-wide traffic",
        "no_bot_signal": "no signs of automated traffic",
    }
    plain_fail = {
        "history": "the article has less than two years of history in the window",
        "volume": f"the audience is small (median {m['median_daily_views']:g} views per day), so percentages swing easily",
        "significance": "the month-to-month trend is not statistically clear",
        "robust_to_spikes": f"much of the change comes from a few spike days (without them: "
                            f"{_pct(m['growth_yoy_no_spikes_pct'])})",
        "concentration": f"{m['top5_days_share_pct']}% of the year's views came on just 5 days",
        "normalization_agrees": f"raw views changed {_pct(m['growth_yoy_raw_pct'])} while the whole wiki changed "
                                f"{_pct(m['wiki_traffic_yoy_pct'])}, so the picture depends on the adjustment",
        "no_bot_signal": "a spike served almost only to desktop looks automated",
    }
    good = [plain_ok[c["name"]] for c in r["checks"] if c["ok"] and c["name"] in plain_ok]
    bad = [plain_fail[c["name"]] for c in r["checks"] if not c["ok"] and c["name"] in plain_fail]
    text = f"Confidence {r['confidence']}"
    if bad:
        text += " because " + "; ".join(bad)
        if good:
            text += ". In favour: " + "; ".join(good[:3])
    else:
        text += ": " + "; ".join(good)
    return text + "."


def spikes_sentence(r: dict) -> str | None:
    spikes = r.get("spikes") or []
    if not spikes:
        return None
    parts = []
    for s in spikes:
        kind = "seasonal, recurs every year" if s.get("recurring_yearly") else "one-off"
        parts.append(f"{s['peak_date']} ({s['peak_ratio']:g}x normal, {kind})")
    text = "Spike days: " + ", ".join(parts) + "."
    m = r["metrics"]
    if m["growth_yoy_no_spikes_pct"] is not None and m["growth_yoy_pct"] is not None \
            and abs(m["growth_yoy_no_spikes_pct"] - m["growth_yoy_pct"]) >= 3:
        text += f" Without spike days the year-over-year change is {_pct(m['growth_yoy_no_spikes_pct'])}."
    return text + " Do not guess their causes."


def timing_sentence(r: dict) -> str | None:
    m = r["metrics"]
    g, g3 = m["growth_yoy_pct"], m["growth_recent_3m_pct"]
    if g3 is None:
        return None
    text = f"Most recent 3 months vs the same months a year earlier: {_pct(g3)}"
    if g is not None and abs(g3) >= 5 and (g3 > 0) != (g > 0):
        text += " (the opposite direction, so the change may be levelling off)"
    return text + "."


def series_sentence(r: dict, multi_topic: bool) -> str:
    m = r["metrics"]
    label = series_label(r["lang"], r["topic"] if multi_topic else None)
    lname = lang_name(r["lang"])
    if r["confidence"] == "Insufficient":
        return (f"{label}: {WORDING['insufficient_data']} (median {m['median_daily_views']:g} views per day, "
                f"about {_int(m['views_avg_month'])} views per month); its year-over-year figure is not interpretable.")
    claim = r["allowed_claims"][0]
    return (f"{label}: interest is {WORDING[claim]}. Its share of all {lname}-language Wikipedia views changed "
            f"{_pct(m['growth_yoy_pct'])} year over year (last 12 months vs the previous 12); raw views changed "
            f"{_pct(m['growth_yoy_raw_pct'])} while the whole wiki changed {_pct(m['wiki_traffic_yoy_pct'])}. "
            f"About {_int(m['views_avg_month'])} views per month ({m['views_per_million']:g} per million wiki views).")


def _weights_text(w: dict) -> str:
    return ", ".join(f"{_WEIGHT_NAMES[k]} {round(v * 100)}%" for k, v in w.items() if v)


def ranking_sentences(summary: dict) -> list[str]:
    ranked = [x for x in summary["ranking"] if x.get("rank")]
    if not ranked:
        return ["No option has enough data to be ranked; do not present any order as a priority."]
    if len(ranked) < 2:
        return []
    multi = len({r["topic"] for r in summary["results"]}) > 1
    name = lambda x: series_label(x["lang"], x["topic"] if multi else None)
    out = [f"Ranking by the stated criteria ({_weights_text(summary['ranking_weights'])}): "
           + "; ".join(f"{x['rank']}. {name(x)}" for x in ranked) + "."]
    alt = []
    for key in ("growth", "volume"):
        w = {k: (1.0 if k == key else 0.0) for k in DEFAULT_WEIGHTS}
        top = next(x for x in rank(summary["results"], w) if x.get("rank"))
        if top["lang"] != ranked[0]["lang"] or top["topic"] != ranked[0]["topic"]:
            alt.append(f"judged on {_WEIGHT_NAMES[key]} alone, {name(top)} would lead")
    if alt:
        out.append("Sensitivity: " + "; ".join(alt) + ".")
    return out


def build_draft(summary: dict) -> dict:
    results = summary["results"]
    multi = len({r["topic"] for r in results} | {m["topic"] for m in summary["missing"]}) > 1
    order = {(x["topic"], x["lang"]): x.get("rank") or 99 for x in summary["ranking"]}
    results = sorted(results, key=lambda r: order.get((r["topic"], r["lang"]), 99))

    per_series = []
    for r in results:
        lines = [series_sentence(r, multi)]
        if r["confidence"] != "Insufficient":
            lines.append(confidence_reasons(r))
        for extra in (timing_sentence(r), spikes_sentence(r)):
            if extra:
                lines.append(extra)
        if r.get("basket_missing"):
            lines.append(f"Compared on fewer articles: {', '.join(r['basket_missing'])} has no article here.")
        per_series.append({"lang": r["lang"], "topic": r["topic"], "claim": r["allowed_claims"][0],
                           "lines": lines})
    missing = [f"{series_label(m['lang'], m['topic'] if multi else None)}: no dedicated article on "
               f"'{m['topic']}', so there is no data and no comparison is possible for this language."
               for m in summary["missing"]]

    topics = []
    for t in summary["topics"]:
        analysed = "; ".join(t["items"])
        line = f"Analysed concept for '{t['label']}': {analysed}."
        if t.get("ambiguous"):
            line += (" This name is ambiguous. State the analysed meaning in the first sentence and offer to run: "
                     + "; ".join(t.get("alternatives", [])[:3]) + ".")
        topics.append(line)
    single = all(len(r["articles"]) == 1 for r in results) and results
    if single:
        topics.append("Each language is measured with one article: "
                      + ", ".join(f"{r['lang']}: {r['articles'][0]}" for r in results) + ".")

    langs_all = list(dict.fromkeys([r["lang"] for r in results] + [m["lang"] for m in summary["missing"]]))
    limits = [f"These results describe readers of the {', '.join(lang_name(l) for l in langs_all)}-language "
              "editions of Wikipedia, not countries: a language edition is not a country, and many people read "
              "English Wikipedia instead of their own language.",
              "Pageviews measure attention (curiosity, study, news), not willingness to pay; use them to decide "
              "what to validate next."]

    headline_bits = [f"{lang_name(r['lang'])} {_pct(r['metrics']['growth_yoy_pct'])} ({WORDING[r['allowed_claims'][0]]})"
                     if r["confidence"] != "Insufficient" else f"{lang_name(r['lang'])}: too little data"
                     for r in results[:3]]
    headline_bits += [f"{lang_name(m['lang'])}: no article" for m in summary["missing"][:2]]
    topic_label = ", ".join(dict.fromkeys(t["label"] for t in summary["topics"]))
    findings = []
    for s, r in zip(per_series, results):
        text = s["lines"][0]
        if r["confidence"] != "Insufficient":
            text = (f"{series_label(r['lang'], r['topic'] if multi else None)}: {WORDING[s['claim']]}; share of wiki "
                    f"views {_pct(r['metrics']['growth_yoy_pct'])} year over year, raw views "
                    f"{_pct(r['metrics']['growth_yoy_raw_pct'])}, about {_int(r['metrics']['views_avg_month'])} "
                    f"views per month. Confidence {r['confidence']}.")
        findings.append({"text": text[:300], "about": [f"{r['topic']}@{r['lang']}" if multi else r["lang"]],
                         "claim": s["claim"]})
    for m in summary["missing"]:
        findings.append({"text": f"{series_label(m['lang'])}: no dedicated article on '{m['topic']}'.",
                         "about": [f"{m['topic']}@{m['lang']}" if multi else m["lang"]], "claim": "no_article"})

    narrative = {
        "title": f"Wikipedia interest: {topic_label}"[:90],
        "headline": ("Interest in " + topic_label + " (share of each Wikipedia's views, year over year): "
                     + "; ".join(headline_bits))[:240],
        "findings": findings[:5],
        "recommendation": "",
        "next_steps": ["Validate demand directly in the top option (landing page, survey or ad test) before building.",
                       "Re-run this study in 3 months to see whether the direction holds."],
    }
    return {
        "how_to_use": ("Translate these sentences into the user's language keeping every number and hedge; "
                       "keep the order. Add your product recommendation (go / don't go / validate first, and what "
                       "evidence would change it). For the PDF: translate narrative_draft, fill 'recommendation', "
                       "save it and run the report command."),
        "topics": topics,
        "per_series": per_series,
        "missing": missing,
        "ranking": ranking_sentences(summary),
        "limits": limits,
        "narrative_draft": narrative,
    }
