"""Plain-language interpretation generated by code, so a small model does not have to invent
wording. Evaluations showed that cheap models copy numbers correctly but lose points when they
phrase things themselves ("views fell 44%" for a share change, "Poland" for Polish Wikipedia,
"clearly declining" on moderate evidence, hand-computed ratios, "all markets" generalisations,
invented reasons). This module writes the whole answer once, correctly: the agent translates it
and adapts the recommendation to the user's product.
"""
from __future__ import annotations

from .langs import lang_name
from .rank import DEFAULT_WEIGHTS, rank

WORDING = {
    "strong_growth": "clearly growing", "growth": "growing (moderate evidence)",
    "possible_growth": "possibly growing, but the evidence is weak",
    "stable": "roughly stable",
    "strong_decline": "clearly declining", "decline": "declining (moderate evidence)",
    "possible_decline": "possibly declining, but the evidence is weak",
    "insufficient_data": "impossible to judge: too little data",
}
_WEIGHT_NAMES = {"growth": "momentum", "volume": "audience size", "share": "share of the wiki",
                 "confidence": "evidence quality"}
# Language editions read across many countries: say so when a user thinks in "markets".
MULTI_COUNTRY = {
    "en": "readers worldwide", "es": "Spain and Latin America", "pt": "Brazil, Portugal and others",
    "fr": "France, Belgium, Switzerland, Canada and Africa", "de": "Germany, Austria and Switzerland",
    "ar": "many Arab countries", "ru": "Russia and many other countries",
    "zh": "mainland China, Taiwan, Hong Kong, Singapore and others", "nl": "the Netherlands and Belgium",
    "sv": "Sweden and Finland", "sr": "Serbia and neighbouring countries", "hr": "Croatia and Bosnia and Herzegovina",
}
LOW_VOLUME = 10   # median views/day below which the draft warns that the evidence is weak


def _pct(x: float | None) -> str:
    return "n/a" if x is None else f"{x:+.1f}%"


def _int(x: float | int | None) -> str:
    return "n/a" if x is None else f"{int(round(x)):,}"


def series_label(lang: str, topic: str | None = None) -> str:
    base = f"{lang_name(lang)}-language Wikipedia ({lang})"
    return f"{topic} on {base}" if topic else base


def _months(summary: dict) -> int:
    return summary.get("window", {}).get("analysis_months", 24)


def confidence_reasons(r: dict, months: int) -> str:
    m = r["metrics"]
    flat = r["direction"] == "flat"
    plain_ok = {
        "history": f"{months} months of data",
        "volume": f"a solid audience (median {m['median_daily_views']:g} views per day)",
        "significance": "no clear trend in either direction" if flat else "the month-to-month trend is statistically clear",
        "robust_to_spikes": "the change is not driven by one-off spike days",
        "concentration": "views are spread over the year rather than a few days",
        "no_bot_signal": "no signs of automated traffic",
    }
    plain_fail = {
        "history": "the article did not exist for the whole period",
        "volume": f"the audience is small (median {m['median_daily_views']:g} views per day), so percentages swing easily",
        "significance": ("the year-over-year change is small, but the longer trend over the period is statistically "
                         "significant, so the picture is mixed") if flat
        else "the month-to-month trend is not statistically clear",
        "robust_to_spikes": f"much of the change comes from a few spike days (without them: "
                            f"{_pct(m['growth_yoy_no_spikes_pct'])})",
        "concentration": f"{m['top5_days_share_pct']}% of the year's views came on just 5 days",
        "no_bot_signal": "one spike was served almost only to desktop computers, which looks automated",
    }
    good = [plain_ok[c["name"]] for c in r.get("checks", []) if c["ok"] and c["name"] in plain_ok]
    bad = [plain_fail[c["name"]] for c in r.get("checks", []) if not c["ok"] and c["name"] in plain_fail]
    text = f"Confidence {r['confidence']}"
    if bad:
        text += " because " + "; ".join(bad)
        if good:
            text += ". In favour: " + "; ".join(good[:3])
    elif good:
        text += ": " + "; ".join(good)
    return text + "."


def short_reason(r: dict) -> str:
    """Compact confidence reason for the PDF findings."""
    failed = [c["name"] for c in r.get("checks", []) if not c["ok"]]
    words = {"volume": "small audience", "significance": "trend not clear month to month",
             "robust_to_spikes": "driven by spike days", "concentration": "views concentrated on a few days",
             "no_bot_signal": "possible bot spike",
             "history": "article is new"}
    if not failed:
        return f"Confidence {r['confidence']}: all checks passed"
    return f"Confidence {r['confidence']}: " + ", ".join(words.get(f, f) for f in failed)


def spikes_sentence(r: dict) -> str | None:
    spikes = r.get("spikes") or []
    if not spikes:
        return None
    parts = []
    for s in spikes:
        kind = "recurs around the same date every year" if s.get("recurring_yearly") else "one-off"
        parts.append(f"{s['peak_date']} ({s['peak_ratio']:g}x normal, {kind})")
    text = "Spike days: " + ", ".join(parts) + "."
    m = r["metrics"]
    if m["growth_yoy_no_spikes_pct"] is not None and m["growth_yoy_pct"] is not None \
            and abs(m["growth_yoy_no_spikes_pct"] - m["growth_yoy_pct"]) >= 3:
        text += f" Without spike days the year-over-year change is {_pct(m['growth_yoy_no_spikes_pct'])}."
    return text


def timing_sentence(r: dict) -> str | None:
    m = r["metrics"]
    g, g3 = m["growth_yoy_pct"], m["growth_recent_3m_pct"]
    if g3 is None:
        return None
    text = f"Most recent 3 months: share of views {_pct(g3)} vs the same months a year earlier"
    if m.get("views_avg_month_recent_3m") is not None and m.get("views_avg_month_recent_3m_year_ago") is not None:
        text += (f" (raw views: about {_int(m['views_avg_month_recent_3m'])} per month, vs about "
                 f"{_int(m['views_avg_month_recent_3m_year_ago'])} in those months a year earlier)")
    if g is not None and abs(g3) >= 5 and (g3 > 0) != (g > 0):
        text += "; this is the opposite direction, so the change may be levelling off"
    elif g is not None and abs(g) >= 10 and abs(g3) < abs(g) / 2 and (g3 > 0) == (g > 0):
        text += "; most of the change happened earlier in the year"
    return text + "."


def series_sentence(r: dict, multi_topic: bool, months: int) -> str:
    m = r["metrics"]
    label = series_label(r["lang"], r["topic"] if multi_topic else None)
    lname = lang_name(r["lang"])
    if r["confidence"] == "Insufficient":
        return (f"{label}: {WORDING['insufficient_data']} (median {m['median_daily_views']:g} views per day, "
                f"about {_int(m['views_avg_month'])} views per month); its year-over-year figure is not interpretable.")
    claim = r["allowed_claims"][0]
    text = (f"{label}: interest is {WORDING[claim]}. Its share of all {lname}-language Wikipedia views changed "
            f"{_pct(m['growth_yoy_pct'])} year over year (last 12 months vs the previous 12); raw views changed "
            f"{_pct(m['growth_yoy_raw_pct'])} while the whole wiki changed {_pct(m['wiki_traffic_yoy_pct'])}. "
            f"About {_int(m['views_avg_month'])} views per month on average over the last 12 months"
            + (f" (about {_int(m['views_avg_month_prev_12m'])} in the previous 12)"
               if m.get("views_avg_month_prev_12m") is not None else "")
            + f"; {m['views_per_million']:g} per million views of that wiki.")
    if months > 24 and m["trend_per_year_pct"] is not None:
        text += f" Trend over the whole {months}-month period: {_pct(m['trend_per_year_pct'])} per year."
    if m["median_daily_views"] < LOW_VOLUME:
        text += " The audience is very small, so treat this as weak evidence."
    return text


def _weights_text(w: dict) -> str:
    return ", ".join(f"{_WEIGHT_NAMES[k]} {round(v * 100)}%" for k, v in w.items() if v)


def ranking_sentences(summary: dict) -> list[str]:
    ranked = [x for x in summary["ranking"] if x.get("rank")]
    if not ranked:
        return ["No option has enough data to be ranked, so no order of priority can be given."]
    if len(ranked) < 2:
        return []
    multi = len({r["topic"] for r in summary["results"]}) > 1
    name = lambda x: series_label(x["lang"], x["topic"] if multi else None)
    out = [f"Ranking by the stated criteria ({_weights_text(summary['ranking_weights'])}): "
           + "; ".join(f"{x['rank']}. {name(x)}" for x in ranked) + "."]
    alt = []
    for key in ("growth", "volume"):
        w = {k: (1.0 if k == key else 0.0) for k in DEFAULT_WEIGHTS}
        top = next(x for x in rank(summary["results"], w) if x.get("rank"))
        if top["lang"] != ranked[0]["lang"] or top["topic"] != ranked[0]["topic"]:
            alt.append(f"judged on {_WEIGHT_NAMES[key]} alone, {name(top)} would lead")
    if alt:   # same sentence as the ranking: evaluations showed a separate trade-off line gets dropped
        out[0] = out[0][:-1] + "; trade-off: " + "; ".join(alt) + "."
    return out


def comparison_sentences(results: list[dict], multi: bool) -> list[str]:
    """Pre-computed comparisons so the agent never divides numbers itself."""
    rows = [r for r in results if r["metrics"]["views_avg_month"] and r["confidence"] != "Insufficient"]
    if len(rows) < 2:
        return []
    name = lambda r: series_label(r["lang"], r["topic"] if multi else None)
    lead = max(rows, key=lambda r: r["metrics"]["views_avg_month"])
    out = [f"Largest audience: {name(lead)} ({_int(lead['metrics']['views_avg_month'])} views per month)."]
    for r in sorted(rows, key=lambda r: -r["metrics"]["views_avg_month"]):
        if r is lead:
            continue
        a, b = lead["metrics"]["views_avg_month"], r["metrics"]["views_avg_month"]
        out.append(f"{name(lead)} has {a / b:.2f}x the monthly views of {name(r)} ({(a / b - 1) * 100:+.0f}%).")
    share = [r for r in rows if r["metrics"]["views_per_million"]]
    if len(share) >= 2:
        top = max(share, key=lambda r: r["metrics"]["views_per_million"])
        low = min(share, key=lambda r: r["metrics"]["views_per_million"])
        if top is not low:
            out.append(f"Highest share of its wiki's views: {name(top)} ({top['metrics']['views_per_million']:g} per "
                       f"million views, vs {low['metrics']['views_per_million']:g} on {name(low)}, the lowest).")
    return out


def recent_sentence(results: list[dict], multi: bool) -> str | None:
    rows = [r for r in results if r["metrics"]["growth_recent_3m_pct"] is not None and r["confidence"] != "Insufficient"]
    if len(rows) < 2:
        return None
    body = "; ".join(f"{series_label(r['lang'], r['topic'] if multi else None)} {_pct(r['metrics']['growth_recent_3m_pct'])}"
                     for r in rows)
    mixed = len({r["metrics"]["growth_recent_3m_pct"] > 0 for r in rows}) > 1
    return f"Most recent 3 months vs a year earlier: {body}." + (" The directions differ between languages." if mixed else "")


def overall_sentence(results: list[dict]) -> str | None:
    """The only allowed generalisation across languages."""
    rows = [r for r in results if r["confidence"] != "Insufficient"]
    if len(rows) < 2:
        return None
    dirs = {r["direction"] for r in rows}
    if dirs == {"down"}:
        return "Across all compared languages with enough data, interest is declining; the strength of evidence differs (see above)."
    if dirs == {"up"}:
        return "Across all compared languages with enough data, interest is growing; the strength of evidence differs (see above)."
    return "The languages do not move in the same direction, so there is no single overall trend."


def direct_answer(summary: dict, results: list[dict], multi: bool) -> str:
    parts = []
    for r in results:
        name = series_label(r["lang"], r["topic"] if multi else None)
        if r["confidence"] == "Insufficient":
            parts.append(f"on {name} there is too little data to judge")
        else:
            parts.append(f"on {name} it is {WORDING[r['allowed_claims'][0]]} "
                         f"(its share of that wiki's views changed {_pct(r['metrics']['growth_yoy_pct'])} over the "
                         f"last 12 months vs the previous 12)")
    parts += [f"{series_label(m['lang'])} has no dedicated article, so there is no data" for m in summary["missing"]]
    label = ", ".join(dict.fromkeys(t["label"] for t in summary["topics"]))
    text = f"Interest in {label}: " + "; ".join(parts) + "."
    amb = [t for t in summary["topics"] if t.get("ambiguous")]
    if amb:
        t = amb[0]
        text = f"Note: '{t['label']}' has several meanings; this analyses {t['items'][0].split(': ', 1)[-1]}. " + text
    return text


def recommendation_draft(summary: dict, results: list[dict], multi: bool) -> str:
    """A data-grounded default stance; the agent adapts it to the user's product without new facts."""
    usable = [r for r in results if r["confidence"] != "Insufficient"]
    if not usable:
        return ("Do not decide from this data: the articles are missing or too small. Broaden the topic or use "
                "another source first; this changes if a broader topic shows enough readers.")
    ranked = [x for x in summary["ranking"] if x.get("rank")]
    best = next((r for r in usable if ranked and r["lang"] == ranked[0]["lang"] and r["topic"] == ranked[0]["topic"]),
                max(usable, key=lambda r: r["metrics"]["views_avg_month"]))
    name = series_label(best["lang"], best["topic"] if multi else None)
    claim = best["allowed_claims"][0]
    first = f"Of the compared options, start with {name}. " if len(usable) > 1 else ""
    if best["metrics"]["median_daily_views"] < LOW_VOLUME:
        return (f"{first}Treat Wikipedia as weak evidence for {name}: the audience is very small. Validate first "
                f"with a direct demand test; this changes only if the test shows clear demand.")
    if best["direction"] == "up":
        return (f"{first}Interest on {name} is {WORDING[claim]}. Validate first with a small demand test (landing "
                f"page or survey) before building; this changes if the test fails or the growth does not hold "
                f"next quarter.")
    if best["direction"] == "flat":
        return (f"{first}Interest on {name} is roughly stable, so the case rests on audience size, not momentum. "
                f"Validate first with a small demand test; this changes if the test is weak or interest starts to fall.")
    return (f"{first}Treat Wikipedia interest on {name} as a headwind: it is {WORDING[claim]}. Go ahead only if a "
            f"direct demand test is convincing; this changes if the decline levels off in the next 3 months.")


def follow_ups(summary: dict) -> list[str]:
    out = []
    for t in summary["topics"]:
        if t.get("ambiguous") and t.get("alternatives"):
            out.append(f"Analyse another meaning of '{t['label']}' instead: {t['alternatives'][0]}.")
    for m in summary["missing"]:
        if m.get("suggestions"):
            out.append(f"For {lang_name(m['lang'])}, analyse a clearly labelled related article instead "
                       f"(closest found: {', '.join(m['suggestions'][:2])}).")
            break
    out.append("Compare more languages.")
    if summary.get("window", {}).get("months", 24) < 36:
        out.append("Look at a longer period (36 months).")
    if summary.get("ranking_weights") == dict(DEFAULT_WEIGHTS) and len(summary["results"]) > 1:
        out.append("Re-rank with your own criteria (for example audience size over momentum).")
    return out[:3]


def answer_markdown(d: dict, summary: dict) -> str:
    """A complete English chat answer. The agent translates it and fills in PDF_PATH."""
    lines = [f"**{d['direct_answer']}**", ""]
    for s in d["per_series"]:
        lines.append(f"- {s['lines'][0]}")
        lines += [f"  - {x}" for x in s["lines"][1:]]
    lines += [f"- {x}" for x in d["missing"]]
    extra = d["comparisons"] + [x for x in (d.get("recent"), d.get("overall")) if x] + d["ranking"]
    if extra:
        lines.append("")
        lines += [f"- {x}" for x in extra]
    lines += ["", "**What was measured and limits**"] + [f"- {x}" for x in d["topics"] + d["limits"]]
    lines += ["", f"**Recommendation:** {d['recommendation_draft']}", ""]
    ch = summary.get("files", {}).get("charts", {})
    pdf = summary.get("files", {}).get("pdf") or "PDF_PATH"
    lines.append(f"**Files:** PDF report: {pdf}" + (f"; charts: {ch.get('trend')}, {ch.get('growth')}" if ch else ""))
    lines += ["", "**I can also:**"] + [f"- {x}" for x in follow_ups(summary)]
    return "\n".join(lines)


def build_draft(summary: dict) -> dict:
    results = summary["results"]
    months = _months(summary)
    multi = len({r["topic"] for r in results} | {m["topic"] for m in summary["missing"]}) > 1
    order = {(x["topic"], x["lang"]): x.get("rank") or 99 for x in summary["ranking"]}
    results = sorted(results, key=lambda r: order.get((r["topic"], r["lang"]), 99))

    per_series = []
    for r in results:
        lines = [series_sentence(r, multi, months)]
        if r["confidence"] != "Insufficient":
            lines.append(confidence_reasons(r, months))
        for extra in (timing_sentence(r), spikes_sentence(r)):
            if extra:
                lines.append(extra)
        if r.get("basket_missing"):
            lines.append(f"Measured on fewer articles than other languages: {', '.join(r['basket_missing'])} has "
                         f"no article here.")
        per_series.append({"lang": r["lang"], "topic": r["topic"], "claim": r["allowed_claims"][0], "lines": lines})
    missing = [f"{series_label(m['lang'], m['topic'] if multi else None)}: no dedicated article on '{m['topic']}', "
               f"so there is no data and no comparison is possible for this language"
               + (f" (closest related articles: {', '.join(m['suggestions'][:2])}; related, not equivalent)."
                  if m.get("suggestions") else ".")
               for m in summary["missing"]]

    topics = []
    for t in summary["topics"]:
        topics.append(f"Concept analysed for '{t['label']}': {'; '.join(t['items'])}.")
        if t.get("ambiguous"):
            topics.append(f"'{t['label']}' is ambiguous; other meanings: {'; '.join(t.get('alternatives', [])[:3])}.")
    if results and all(len(r["articles"]) == 1 for r in results):
        topics.append("Each language is measured with one article ("
                      + ", ".join(f"{r['lang']}: {r['articles'][0]}" for r in results)
                      + "), which is a proxy for interest in the whole subject.")
    if any(r.get("basket_missing") for r in results):
        topics.append("Languages are measured on different sets of articles (see above), so compare them with care.")

    langs_all = list(dict.fromkeys([r["lang"] for r in results] + [m["lang"] for m in summary["missing"]]))
    limits = [f"These results describe readers of the {', '.join(lang_name(l) for l in langs_all)}-language "
              "editions of Wikipedia, not countries; many people read English Wikipedia instead of their own language."]
    wide = [f"{lang_name(l)}-language Wikipedia is read in {MULTI_COUNTRY[l]}" for l in langs_all if l in MULTI_COUNTRY]
    if wide:
        limits.append("; ".join(wide) + ".")
    limits.append("Pageviews measure attention (curiosity, study, news), not willingness to pay.")

    draft = {
        "direct_answer": direct_answer(summary, results, multi),
        "per_series": per_series,
        "missing": missing,
        "comparisons": comparison_sentences(results, multi),
        "recent": recent_sentence(results, multi),
        "overall": overall_sentence(results),
        "ranking": ranking_sentences(summary),
        "topics": topics,
        "limits": limits,
        "recommendation_draft": recommendation_draft(summary, results, multi),
    }
    draft["answer_markdown"] = answer_markdown(draft, summary)

    topic_label = ", ".join(dict.fromkeys(t["label"] for t in summary["topics"]))
    findings = []
    for s, r in zip(per_series, results):
        if r["confidence"] == "Insufficient":
            text = s["lines"][0]
        else:
            m = r["metrics"]
            text = (f"{series_label(r['lang'], r['topic'] if multi else None)}: {WORDING[s['claim']]}; share of wiki "
                    f"views {_pct(m['growth_yoy_pct'])} year over year (raw views {_pct(m['growth_yoy_raw_pct'])}), "
                    f"about {_int(m['views_avg_month'])} views per month; last 3 months "
                    f"{_pct(m['growth_recent_3m_pct'])}. {short_reason(r)}.")
        if len(text) > 300:   # keep whole numbers: drop the least important clause instead of cutting
            text = text.replace(f" {short_reason(r)}.", "")[:300]
        findings.append({"text": text, "about": [f"{r['topic']}@{r['lang']}" if multi else r["lang"]],
                         "claim": s["claim"]})
    for m in summary["missing"]:
        findings.append({"text": f"{series_label(m['lang'])}: no dedicated article on '{m['topic']}', so no data.",
                         "about": [f"{m['topic']}@{m['lang']}" if multi else m["lang"]], "claim": "no_article"})
    several = len(results) + len(summary["missing"]) > 1
    headline = draft["direct_answer"]
    if len(headline) > 240:
        amb = next((t for t in summary["topics"] if t.get("ambiguous")), None)
        if amb:   # keep the analysed meaning visible in the PDF headline
            concept = amb["items"][0].split(": ", 1)[-1].split(" — ")
            topic_label = f"{concept[0]} ({concept[1][:40].rsplit(' ', 1)[0]})" if len(concept) > 1 else concept[0]
        parts = [f"{lang_name(r['lang'])} {_pct(r['metrics']['growth_yoy_pct'])}" if r["confidence"] != "Insufficient"
                 else f"{lang_name(r['lang'])}: too little data" for r in results]
        parts += [f"{lang_name(m['lang'])}: no article" for m in summary["missing"]]
        headline = (f"Interest in {topic_label} ({'share of each wiki' if several else 'share of wiki'} views, "
                    f"year over year): " + "; ".join(parts))
        if len(headline) > 240:
            headline = headline[:240].rsplit(";", 1)[0]
    draft["narrative_draft"] = {
        "title": f"Wikipedia interest: {topic_label}"[:90],
        "headline": headline,
        "findings": findings[:5],
        "recommendation": draft["recommendation_draft"][:420],
        "next_steps": ["Run a small direct demand test (landing page, survey or ads) before building.",
                       "Re-run this study in 3 months to check that the direction holds."],
    }
    draft["how_to_use"] = ("answer_markdown is the complete chat answer: translate it into the user's language, keep "
                           "every number, hedge and date, adapt only the Recommendation line to the user's product "
                           "(no new facts), and replace PDF_PATH. narrative_draft is the PDF text: translate it the "
                           "same way and run the report command.")
    return draft
