"""Report/chart labels and the fixed method & limitations text.

The caveats are generated by code (not by the agent) so every report carries them, in the
reader's language. Unsupported languages fall back to English; the agent's own narrative can
still be written in any language.
"""
from __future__ import annotations

_EN = {
    "trend_title": "Interest: views per million wiki pageviews",
    "trend_axis": "views per million",
    "growth_title": "Change in interest: last 12 mo vs previous 12",
    "growth_axis": "% change of share of wiki traffic",
    "low_conf_legend": "hatched = low / insufficient confidence",
    "report_title": "Wikipedia interest report",
    "takeaway": "Key takeaway",
    "recommendation": "Recommendation",
    "findings": "Findings",
    "next_steps": "Next steps",
    "comparison": "Comparison",
    "col_option": "Language / topic",
    "col_views": "Avg views / month",
    "col_share": "Per million",
    "col_growth": "YoY (share)",
    "col_trend": "Trend / yr",
    "col_conf": "Confidence",
    "missing": "no article",
    "method": "Method & limitations",
    "window": "Window",
    "source": "Source: Wikimedia Pageviews API (agent=user) and Wikidata; generated",
    "High": "High", "Medium": "Medium", "Low": "Low", "Insufficient": "Insufficient",
    "method_text": (
        "Views include redirects to each article and only human traffic (agent=user). Growth compares the "
        "last 12 months with the previous 12 using the article's share of all pageviews of that Wikipedia, so "
        "wiki-wide traffic shifts are neutralised; raw views show audience size. Confidence combines data "
        "history, volume, a seasonal Mann-Kendall trend test, robustness to spike days, concentration of "
        "views, agreement of raw and normalised growth, and a desktop-only bot check."),
    "limits_text": (
        "Pageviews measure attention to an article, not purchase intent or willingness to pay. A language "
        "edition is not a country, and many people read Wikipedia in English instead of their own language. "
        "Article coverage and naming differ between wikis; missing articles are reported, not estimated. "
        "Use these results to choose what to validate next, not as a final market-size estimate."),
}

_UK = {
    "trend_title": "Інтерес: перегляди на мільйон переглядів вікі",
    "trend_axis": "переглядів на мільйон",
    "growth_title": "Зміна інтересу: останні 12 місяців проти попередніх 12",
    "growth_axis": "% зміни частки трафіку вікі",
    "low_conf_legend": "штрихування = низька / недостатня довіра",
    "report_title": "Звіт про інтерес у Вікіпедії",
    "takeaway": "Головний висновок",
    "recommendation": "Рекомендація",
    "findings": "Спостереження",
    "next_steps": "Наступні кроки",
    "comparison": "Порівняння",
    "col_option": "Мова / тема",
    "col_views": "Сер. переглядів / міс.",
    "col_share": "На мільйон",
    "col_growth": "Р/р (частка)",
    "col_trend": "Тренд / рік",
    "col_conf": "Довіра",
    "missing": "статті немає",
    "method": "Метод і обмеження",
    "window": "Період",
    "source": "Джерело: Wikimedia Pageviews API (agent=user) та Wikidata; згенеровано",
    "High": "Висока", "Medium": "Середня", "Low": "Низька", "Insufficient": "Недостатньо даних",
    "method_text": (
        "Перегляди включають перенаправлення на статтю і лише трафік людей (agent=user). Зростання порівнює "
        "останні 12 місяців із попередніми 12 за часткою статті в усіх переглядах відповідної Вікіпедії, тож "
        "зміни загального трафіку вікі нейтралізовано; абсолютні перегляди показують розмір аудиторії. Довіра "
        "враховує тривалість даних, обсяг, сезонний тест Манна-Кендалла, стійкість до пікових днів, концентрацію "
        "переглядів, узгодженість абсолютного й нормалізованого зростання та перевірку на ботів (лише desktop)."),
    "limits_text": (
        "Перегляди вимірюють увагу до статті, а не намір купити чи готовність платити. Мовний розділ — це не "
        "країна, і багато людей читають Вікіпедію англійською замість рідної мови. Покриття та назви статей "
        "різняться між розділами; відсутні статті зазначено, а не оцінено. Використовуйте результати, щоб "
        "обрати, що перевіряти далі, а не як остаточну оцінку ринку."),
}

_PL = {
    "trend_title": "Zainteresowanie: wyświetlenia na milion odsłon wiki",
    "trend_axis": "wyświetlenia na milion",
    "growth_title": "Zmiana zainteresowania: ostatnie 12 miesięcy vs poprzednie 12",
    "growth_axis": "% zmiany udziału w ruchu wiki",
    "low_conf_legend": "kreskowanie = niska / niewystarczająca pewność",
    "report_title": "Raport zainteresowania w Wikipedii",
    "takeaway": "Główny wniosek",
    "recommendation": "Rekomendacja",
    "findings": "Obserwacje",
    "next_steps": "Następne kroki",
    "comparison": "Porównanie",
    "col_option": "Język / temat",
    "col_views": "Śr. wyświetleń / mies.",
    "col_share": "Na milion",
    "col_growth": "R/R (udział)",
    "col_trend": "Trend / rok",
    "col_conf": "Pewność",
    "missing": "brak artykułu",
    "method": "Metoda i ograniczenia",
    "window": "Okres",
    "source": "Źródło: Wikimedia Pageviews API (agent=user) i Wikidata; wygenerowano",
    "High": "Wysoka", "Medium": "Średnia", "Low": "Niska", "Insufficient": "Za mało danych",
    "method_text": (
        "Wyświetlenia obejmują przekierowania do artykułu i tylko ruch ludzki (agent=user). Wzrost porównuje "
        "ostatnie 12 miesięcy z poprzednimi 12 na podstawie udziału artykułu we wszystkich odsłonach danej "
        "Wikipedii, co neutralizuje zmiany ruchu całej wiki; surowe wyświetlenia pokazują wielkość odbiorców. "
        "Pewność łączy długość danych, wolumen, sezonowy test Manna-Kendalla, odporność na dni szczytowe, "
        "koncentrację wyświetleń, zgodność wzrostu surowego i znormalizowanego oraz test botów (tylko desktop)."),
    "limits_text": (
        "Wyświetlenia mierzą uwagę poświęconą artykułowi, a nie zamiar zakupu. Wersja językowa to nie kraj, a "
        "wiele osób czyta Wikipedię po angielsku zamiast w swoim języku. Pokrycie i nazwy artykułów różnią się "
        "między wersjami; brakujące artykuły są zgłaszane, a nie szacowane. Wyniki służą do wyboru, co "
        "zweryfikować dalej, a nie jako ostateczna ocena rynku."),
}

_CS = {
    "trend_title": "Zájem: zobrazení na milion zobrazení wiki",
    "trend_axis": "zobrazení na milion",
    "growth_title": "Změna zájmu: posledních 12 měsíců vs předchozích 12",
    "growth_axis": "% změna podílu na provozu wiki",
    "low_conf_legend": "šrafování = nízká / nedostatečná důvěra",
    "report_title": "Zpráva o zájmu na Wikipedii",
    "takeaway": "Hlavní závěr",
    "recommendation": "Doporučení",
    "findings": "Zjištění",
    "next_steps": "Další kroky",
    "comparison": "Srovnání",
    "col_option": "Jazyk / téma",
    "col_views": "Prům. zobrazení / měs.",
    "col_share": "Na milion",
    "col_growth": "Meziročně (podíl)",
    "col_trend": "Trend / rok",
    "col_conf": "Důvěra",
    "missing": "článek chybí",
    "method": "Metoda a omezení",
    "window": "Období",
    "source": "Zdroj: Wikimedia Pageviews API (agent=user) a Wikidata; vytvořeno",
    "High": "Vysoká", "Medium": "Střední", "Low": "Nízká", "Insufficient": "Nedostatek dat",
    "method_text": (
        "Zobrazení zahrnují přesměrování na článek a pouze lidský provoz (agent=user). Růst porovnává posledních "
        "12 měsíců s předchozími 12 podle podílu článku na všech zobrazeních dané Wikipedie, takže změny provozu "
        "celé wiki jsou neutralizovány; absolutní zobrazení ukazují velikost publika. Důvěra kombinuje délku dat, "
        "objem, sezónní Mann-Kendallův test, odolnost vůči špičkám, koncentraci zobrazení, shodu absolutního a "
        "normalizovaného růstu a kontrolu botů (pouze desktop)."),
    "limits_text": (
        "Zobrazení měří pozornost věnovanou článku, ne úmysl nakoupit. Jazyková verze není země a mnoho lidí čte "
        "Wikipedii anglicky místo ve svém jazyce. Pokrytí a názvy článků se mezi verzemi liší; chybějící články "
        "jsou uvedeny, ne odhadnuty. Výsledky slouží k výběru toho, co ověřit dál, ne jako konečný odhad trhu."),
}

_DE = {
    "trend_title": "Interesse: Aufrufe pro Million Wiki-Aufrufe",
    "trend_axis": "Aufrufe pro Million",
    "growth_title": "Veränderung des Interesses: letzte 12 Monate vs. vorherige 12",
    "growth_axis": "% Veränderung des Anteils am Wiki-Traffic",
    "low_conf_legend": "schraffiert = geringe / unzureichende Belastbarkeit",
    "report_title": "Wikipedia-Interessenbericht",
    "takeaway": "Kernaussage",
    "recommendation": "Empfehlung",
    "findings": "Befunde",
    "next_steps": "Nächste Schritte",
    "comparison": "Vergleich",
    "col_option": "Sprache / Thema",
    "col_views": "Ø Aufrufe / Monat",
    "col_share": "Pro Million",
    "col_growth": "Vorjahr (Anteil)",
    "col_trend": "Trend / Jahr",
    "col_conf": "Belastbarkeit",
    "missing": "kein Artikel",
    "method": "Methode & Grenzen",
    "window": "Zeitraum",
    "source": "Quelle: Wikimedia Pageviews API (agent=user) und Wikidata; erstellt",
    "High": "Hoch", "Medium": "Mittel", "Low": "Gering", "Insufficient": "Zu wenig Daten",
    "method_text": (
        "Aufrufe enthalten Weiterleitungen auf den Artikel und nur menschlichen Traffic (agent=user). Das Wachstum "
        "vergleicht die letzten 12 Monate mit den vorherigen 12 anhand des Anteils des Artikels an allen Aufrufen "
        "der jeweiligen Wikipedia, sodass Wiki-weite Traffic-Änderungen neutralisiert sind; absolute Aufrufe "
        "zeigen die Publikumsgröße. Die Belastbarkeit kombiniert Datenhistorie, Volumen, einen saisonalen "
        "Mann-Kendall-Test, Robustheit gegenüber Spitzentagen, Konzentration, Übereinstimmung von absolutem und "
        "normalisiertem Wachstum sowie eine Bot-Prüfung (nur Desktop)."),
    "limits_text": (
        "Aufrufe messen Aufmerksamkeit für einen Artikel, nicht Kaufabsicht. Eine Sprachversion ist kein Land, und "
        "viele Menschen lesen Wikipedia auf Englisch statt in ihrer Sprache. Abdeckung und Titel unterscheiden sich "
        "zwischen Wikis; fehlende Artikel werden gemeldet, nicht geschätzt. Nutzen Sie die Ergebnisse, um zu "
        "entscheiden, was als Nächstes geprüft wird, nicht als endgültige Marktgröße."),
}

_ES = {
    "trend_title": "Interés: vistas por millón de vistas de la wiki",
    "trend_axis": "vistas por millón",
    "growth_title": "Cambio de interés: últimos 12 meses vs 12 anteriores",
    "growth_axis": "% de cambio de la cuota del tráfico wiki",
    "low_conf_legend": "rayado = confianza baja / insuficiente",
    "report_title": "Informe de interés en Wikipedia",
    "takeaway": "Conclusión principal",
    "recommendation": "Recomendación",
    "findings": "Hallazgos",
    "next_steps": "Próximos pasos",
    "comparison": "Comparación",
    "col_option": "Idioma / tema",
    "col_views": "Vistas medias / mes",
    "col_share": "Por millón",
    "col_growth": "Interanual (cuota)",
    "col_trend": "Tendencia / año",
    "col_conf": "Confianza",
    "missing": "sin artículo",
    "method": "Método y limitaciones",
    "window": "Periodo",
    "source": "Fuente: Wikimedia Pageviews API (agent=user) y Wikidata; generado",
    "High": "Alta", "Medium": "Media", "Low": "Baja", "Insufficient": "Datos insuficientes",
    "method_text": (
        "Las vistas incluyen redirecciones al artículo y solo tráfico humano (agent=user). El crecimiento compara "
        "los últimos 12 meses con los 12 anteriores usando la cuota del artículo en todas las vistas de esa "
        "Wikipedia, de modo que se neutralizan los cambios de tráfico de toda la wiki; las vistas absolutas "
        "muestran el tamaño de la audiencia. La confianza combina historial, volumen, una prueba estacional de "
        "Mann-Kendall, robustez ante picos, concentración, coherencia entre crecimiento absoluto y normalizado y "
        "un control de bots (solo escritorio)."),
    "limits_text": (
        "Las vistas miden atención a un artículo, no intención de compra. Una edición lingüística no es un país, y "
        "mucha gente lee Wikipedia en inglés en lugar de su idioma. La cobertura y los títulos varían entre wikis; "
        "los artículos ausentes se indican, no se estiman. Use estos resultados para decidir qué validar después, "
        "no como estimación final del mercado."),
}

_FR = {
    "trend_title": "Intérêt : vues par million de vues du wiki",
    "trend_axis": "vues par million",
    "growth_title": "Évolution de l'intérêt : 12 derniers mois vs 12 précédents",
    "growth_axis": "% d'évolution de la part du trafic wiki",
    "low_conf_legend": "hachuré = confiance faible / insuffisante",
    "report_title": "Rapport d'intérêt Wikipédia",
    "takeaway": "À retenir",
    "recommendation": "Recommandation",
    "findings": "Constats",
    "next_steps": "Prochaines étapes",
    "comparison": "Comparaison",
    "col_option": "Langue / sujet",
    "col_views": "Vues moy. / mois",
    "col_share": "Par million",
    "col_growth": "Sur 1 an (part)",
    "col_trend": "Tendance / an",
    "col_conf": "Confiance",
    "missing": "pas d'article",
    "method": "Méthode et limites",
    "window": "Période",
    "source": "Source : Wikimedia Pageviews API (agent=user) et Wikidata ; généré",
    "High": "Élevée", "Medium": "Moyenne", "Low": "Faible", "Insufficient": "Données insuffisantes",
    "method_text": (
        "Les vues incluent les redirections vers l'article et uniquement le trafic humain (agent=user). La "
        "croissance compare les 12 derniers mois aux 12 précédents selon la part de l'article dans toutes les vues "
        "de cette Wikipédia, ce qui neutralise les variations de trafic de tout le wiki ; les vues brutes indiquent "
        "la taille de l'audience. La confiance combine l'historique, le volume, un test saisonnier de "
        "Mann-Kendall, la robustesse aux pics, la concentration, la cohérence brut/normalisé et un contrôle des "
        "robots (bureau uniquement)."),
    "limits_text": (
        "Les vues mesurent l'attention portée à un article, pas l'intention d'achat. Une édition linguistique "
        "n'est pas un pays, et beaucoup de gens lisent Wikipédia en anglais plutôt que dans leur langue. La "
        "couverture et les titres diffèrent selon les wikis ; les articles manquants sont signalés, non estimés. "
        "Utilisez ces résultats pour choisir quoi valider ensuite, pas comme estimation finale du marché."),
}

LABELS = {"en": _EN, "uk": _UK, "pl": _PL, "cs": _CS, "de": _DE, "es": _ES, "fr": _FR}
SUPPORTED = tuple(LABELS)


def labels(lang: str) -> dict[str, str]:
    base = dict(_EN)
    base.update(LABELS.get(lang, {}))
    return base
